# Generated by Django 3.1.3 on 2020-11-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201123_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
